- hosts: ubuntu
  tasks: 
  - name: install git 
    apt: name=git state=latest
  - notify: 
    - start git

    - name: install apache maven
      apt: name=apache maven state=latest
    - notify: 
      - start maven

      - name: install jenkins
        apt: name=jenkins state=latest
      - notify: 
      - start jenkins

      - name: install docker 
        apt: name=docker state=latest
      - notify:
        - start docker

      - name: install chef 
        apt: name=chef state=latest
      - notify: 
      - start chef

      - name: apache2
        service: name=apache2 state=start
      

      - name: nginx
        service: name=nginx state=start
      
      - name: tomcat
        service: name=tomcat state=start

